#!/bin/bash

# get the name of the branch we are on
function wip() {
  # watch ip address
  ifconfig | grep 'inet.*netmask.*broadcast' > ipadd

  sed -i '' 's/inet\(.*\)netmask.*/\1/g' ipadd

  cat ipadd && rm ipadd
}
