#!/bin/bash

# copy without newline
copy () { 
  `$1 | tr -d '\n' | pbcopy`; 
}

alias c='copy'

alias ....='cd ../../..'

alias ls1='ls -1'
alias lsil='ls -il'

# git
alias gcd1='git clone --depth=1'

alias chrome='open -a "Google Chrome"'

# open
alias o='open'
alias oo='open .'

# sublime text 2
alias b='/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl'
alias b3='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
# `bb()` is very slow when the folder contain too many files.
subl_template="${HOME}/dotfiles/my-dotfiles/tmpl/subl_template"
function get_sublime_project {
  # TODO: 是否文件夹
  local subl_proj
  subl_proj=`find . -name "*.sublime-project" -d 1 | sort -r | head -1`
  if [[ `echo -n $subl_proj | wc -m` -eq 0 ]]
  then
    # copy structure of sublime-project from template
    S0="${BASH_SOURCE[0]}"
    DIRNAME="$( dirname "$S0")"
    DIR="$( cd "$DIRNAME" && pwd)"
    foler_path=$DIR
    echo $foler_path
    eval "echo \"$(<${subl_template})\" > \"${foler_path}\"\/0.sublime\-project"
    subl_proj='./0.sublime-project'
  fi
  echo "$subl_proj"
}
alias bb='b $(get_sublime_project)'
alias bb3='b3 $(get_sublime_project)'

alias glu='git pull -u'
alias hgll="hg log | grep '^user\?'|cut -d':' -f2|sort|uniq -c|sort -nr"

# mysql
alias mysqlstart='sudo /usr/local/mysql-5.5.30-osx10.6-x86_64/support-files/mysql.server start'
alias mysqlstop='sudo /usr/local/mysql-5.5.30-osx10.6-x86_64/support-files/mysql.server stop' 