#!/bin/bash

# copy without newline
copy () { 
  `$1 | tr -d '\n' | pbcopy`;
}

alias c='copy'
alias cpd='copy pwd'

alias ....='cd ../../..'

alias ls1='ls -1'
alias lsil='ls -il'

# git
alias gcd1='git clone --depth=1'

alias chrome='open -a "Google Chrome"'

# open
alias o='open'
alias oo='open .'

alias gl='git pull'
alias gp='git push'
alias glu='git pull -u'
alias hgll="hg log | grep '^user\?'|cut -d':' -f2|sort|uniq -c|sort -nr"

# mysql
alias mysqlstart='sudo /usr/local/mysql-5.5.30-osx10.6-x86_64/support-files/mysql.server start'
alias mysqlstop='sudo /usr/local/mysql-5.5.30-osx10.6-x86_64/support-files/mysql.server stop' 