#!/bin/bash

# copy without newline
copy () { 
  `$1 | tr -d '\n' | pbcopy`;
}

alias wh='which'
alias c='code'
alias cpd='copy pwd'

alias ....='cd ../../..'

alias ls1='ls -1'
alias lsil='ls -il'

# git
alias gcd1='git clone --depth=1'

alias chrome='open -a "Google Chrome"'

# open
alias o='open'
alias oo='open .'

alias gb='git branch'
alias gbl='git branch -l'
alias gcm='git checkout master'
alias gc='git checkout'
alias gcb='git checkout -b'
alias grb='git rebase'
alias grbm='git rebase master'
alias gl='git pull'
alias gp='git push'
alias glu='git pull -u'
alias hgll="hg log | grep '^user\?'|cut -d':' -f2|sort|uniq -c|sort -nr"


alias pg-start="launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
alias pg-stop="launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
