#!/bin/bash

# git archive
function git_archive_branch {
  git tag archive/$1 $1
  git checkout master
  git branch --delete $1
  git push origin --delete $1
}

# d
function _ddv_find_file {
  folder_name=$1
  zip_name="$1.zip"
  if [[ -d $folder_name ]]; then
    echo "$folder_name"
  elif [[ -f "${zip_name}"  ]]; then
    echo "$zip_name"
  fi
}

# d
function _ddv_open {
  if [[ -d $1 ]]; then
    b3 "$1"
  elif [[ -f "$1"  ]]; then
    unzip "$1" -d "$DDV_DOWNLOAD_DIR/"
    folder=${1:0:${#1}-4}
    if [[ -d $folder ]]; then
      b3 "$folder"
    else
      echo "解压出错!"
    fi
  fi
}

# 下载 github repo 后，解压并在 sublime 中打开项目
function ddv {
  if [ -z "$1" ]; then
    return
  fi
  # 有一些 github repo 不是 master 分支
  local f
  f=$(_ddv_find_file "$DDV_DOWNLOAD_DIR/$1")
  if [ -z "$f" ]; then
    f=$(_ddv_find_file "$DDV_DOWNLOAD_DIR/$1-master")
  fi
  if [ -z "$f" ]; then
    f=$(_ddv_find_file "$DDV_DOWNLOAD_DIR/$1-dev")
  fi
  err=$(_ddv_open "$f")
  echo "$err"
}

