#!/bin/bash

alias np='npm publish'
alias ni='npm install'
alias nid='npm install -D'
# alias nig='cnpm install --global'
# alias clsg='cnpm ls --global'
# alias cis='cnpm install --save'
# alias cid='cnpm install --save-dev'

# alias cuis='cnpm uninstall --save'
# alias cuid='cnpm uninstall --save-dev'

# yarn
alias yr='yarn dev'
alias ys='yarn start'
alias yb='yarn build'
alias yga='yarn global add'
alias ya='yarn add'
alias yad='yarn add -D'
alias ygu='yarn global upgrade --latest'
alias yu='yarn upgrade --latest'
alias yud='yarn upgrade -D --latest'

alias yvue='yarn upgrade vue vue-template-compiler'

# view npm module latest version 
mver() {
  npm view ${1} dist-tags
}
# view module version in node_modules
cver() {
  cat node_modules/${1}/package.json | grep 'version'
}
rver() {
  cat ./package-lock.json | grep -A1 '^    "'${1}'": {'
}
# view module version in package.json
ccver() {
  cat ./package.json | grep "${1}"
}


alias lb="lerna bootstrap"
alias lv="lerna run dev"