#!/bin/bash

# cnpm
alias ci='cnpm install'
alias cig='cnpm install --global'
alias clsg='cnpm ls --global'
alias cis='cnpm install --save'
alias cid='cnpm install --save-dev'

alias cuis='cnpm uninstall --save'
alias cuid='cnpm uninstall --save-dev'


# view npm module latest version 
mver() {
  npm view ${1} dist-tags
}