#!/bin/bash


# sublime text 2
alias _b='/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl'
# sublime text 3
alias _b3='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

# sublime text project file template
subl_template="${HOME}/dotfiles/my-dotfiles/tmpl/subl_template"

function get_sublime_project {
  local subl_proj
  local abs_folder_path
  local run_path
  # If is no input folder param
  if [ -z "$1" ]; then
    run_path=.
  else
    run_path=$1
  fi
  subl_proj=`find $run_path -maxdepth 1 -name "*.sublime-project" -d 1 | sort -r | head -1`
  # echo "$subl_proj"
  # Create if there not exist project file
  if [[ `echo -n $subl_proj | wc -m` -eq 0 ]]
  then
    # If is relative run_path 
    # echo "${run_path:0:1}"
    if [ "${run_path:0:1}" = "/" ]; then
      abs_folder_path=$run_path
    else
      abs_folder_path="$( cd "$run_path" && pwd)"
    fi
    project_name=`basename $abs_folder_path`
    # echo "abs_folder_path: $abs_folder_path"
    # copy structure of sublime-project from template
    # echo "echo \"$(<${subl_template})\" > \"${run_path}\"\/0.sublime\-project"
    subl_proj="$abs_folder_path/$project_name.sublime-project"
    eval "echo \"$(<${subl_template})\" > \"${subl_proj}\""
    # echo "create $subl_proj"
  fi
  echo "$subl_proj"
}

function bfunc {
  if [ -z "$1" ]; then
    return
  fi

  local subl_proj
  local open_file
  # if is a folder
  if [[ -d $1 ]]; then
    # quotes are already added in get_sublime_project
    subl_proj=$(get_sublime_project $1)
    # echo "$subl_proj"
    open_file=$subl_proj
  else
    # No matter file exsits or not, return it back
    # get abs path
    # S0="${BASH_SOURCE[0]}"
    # DIRNAME="$( dirname "$S0")"
    # DIR="$( cd "$DIRNAME" && pwd)"
    open_file=$1
  fi
  echo "$open_file"
}

function b {
  local f
  f=$(bfunc $1)
  # return
  if [ ! -z "$f" ]; then
    echo "open $f"
    _b $f
  fi
}
function b3 {
  local f
  f=$(bfunc $1)
  # return
  if [ ! -z "$f" ]; then
    echo "open $f"
    _b3 $f
  fi
}

alias bb='b .'
alias bb3='b3 .'